### ISSUE TITLE
query fails to recognize patterns with repeated elements

### ISSUE THREAD

**Issue by cmungall** [INCATools/dosdp-tools#139]
I have this

```
equivalentTo:
  text: "('related' some %s) and ('related' some %s)"
  vars:
    - v0
    - v1
```

And this:

![image](https://user-images.githubusercontent.com/50745/59990802-81e25580-95f9-11e9-8698-3268198b7058.png)

(ignore the weirdness for now, this is auto-generated by patternizer)

Yet the class is not matched by query. My hypothesis is that this is due to the fact that the same expression is repeated. Granted this is a weird example, but we can imagine saner analogs.

Test coming...
