### ISSUE TITLE
Passing through of synonyms from TSV to OWL

### ISSUE THREAD

**Issue by cmungall** [INCATools/dosdp-tools#41]
For the @Planteome project we want to be able to curate synonyms in the TSV, and have these exported as synonyms in the OWL

We're having issues figuring out how to do this

**Comment by balhoff** [comment]
This may relate to #40. Either way I will work on them both ASAP.

**Comment by dosumis** [comment]
Please let me know if any clarification needed.

**Comment by balhoff** [comment]
This does work now. I need to clean up the predefined synonym types handling, which changed in the spec after I implemented it. But here is how you do it in the most verbose way:

```yaml
pattern_name: test_pattern

annotationProperties:
  description: dc:description

data_vars:
  extended_description: xsd:string

annotations:
  - annotationProperty: description
    text: "The description is: %s."
    vars:
      - extended_description
    annotations:
      - annotationProperty: description
        text: "We are annotating the annotation axiom."
```

**Comment by dosumis** [comment]
This is how I'm handling it right now.  Doesn't this need a prefixes file with all the OBO prefixes used specified manually + dc prefix?  This could be made easier by adding some more default prefixes on top of the obo ones (OboInOwl, dc, rdfs).

The full spec has two other options:

1. use list_data_var to pass a list of synonyms with same scope (e.g. exact), then use the appropriate property key (e.g.   exact_synonym:).

2. convenience fields for generated synonyms (see #40)

**Comment by cmungall** [comment]
A big ask but it would be lovely to have a readthedocs or similar, it's hard for a lot of people to grok the different ways of doing things via the README

alternatively if there was a toy repo with a mini ontology that could be used as both unit test and exemplar

**Comment by marieALaporte** [comment]
This is what I tried from your response @balhoff 
```
annotationProperties:
  description: oio:hasExactSynonym

data_vars:
  synonyms: xsd:string

annotations:
  - annotationProperty: description
    text: "%s"
    vars:
      - synonyms
```

This what I get:  
`<owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/obo_hasExactSynonym"/>`
