### ISSUE TITLE
Problem with adding ORCIDs as data_list_vars

### ISSUE THREAD

**Issue by rays22** [INCATools/dosdp-tools#418]
I am trying to add a list of ORCIDs 'data_list_vars' without success.

It seems to me that only the DOS-DP OBO fields work with `data_list_vars`. Adding a list of contributors using `data_list_vars` did not work for me.

### files to reproduce the problem: [issue418-test-files.zip](https://github.com/INCATools/dosdp-tools/files/8995105/issue418-test-files.zip)
1. test_data_list_vars.yaml
    - validation: PASS
```
dosdp validate -i test_data_list_vars.yaml
INFO:root:Checking test_data_list_vars.yaml
INFO:root:Validation completed without any issues to report.
```
2. test_data_list_vars.tsv

When I check `definitions.owl` after turning the template table into OWL axioms, I do not find any of the `dcterms:contributor` ORCID data, or the synonyms from the tsv table that I am trying to add under annotations.
Please, note that I can add synonyms as `data_list_vars` in another way ( see `syns2` and the comments in  'test_data_list_vars.yaml').

**Comment by dosumis** [comment]
‘contributor’ is not a key defined in the DOSDP schema <https://github.com/INCATools/dead_simple_owl_design_patterns/blob/master/docs/dosdp_schema.md>.  You need to add this under annotations.

This should work:

**Comment by rays22** [comment]
Test DOS-DP pattern files:
1. test_data_vars.yaml: 

Adding data_list_vars

    exact_synonym:
      value: syns

works all right.

```
dosdp validate -i test_data_vars.yaml        
INFO:root:Checking test_data_vars.yaml
INFO:root:Validation completed without any issues to report.
```
2. test_data_list_vars.yaml

Adding another annotation type does not seem to work.

```
dosdp validate -i test_data_list_vars.yaml
INFO:root:Checking test_data_list_vars.yaml
/Users/ray/py_tools/venv/lib/python3.9/site-packages/dosdp/validator.py:30: UserWarning:deque(['additionalProperties']) => Additional properties are not allowed ('contributor' was unexpected) => []
INFO:root:Validation completed with issues to be fixed.
```

**Comment by rays22** [comment]
I have updated the test files to help reproduce the problem and tried to clarify the issue in the description above.

**Comment by balhoff** [comment]
@rays22 are you defining the prefix `dcterms:` when running your command?

**Comment by rays22** [comment]
> @rays22 are you defining the prefix `dcterms:` when running your command?

I am not sure if I understand your question @balhoff .
No, I am not defining it explicitly `dcterms:` or other prefixes when I am running my make command:

```
sh run.sh make ../patterns/definitions.owl -B IMP=false
```

Here is the relevant part of my yaml:

```
annotationProperties:
  exact_synonym: oio:hasExactSynonym
  contributor: dcterms:contributor

vars:
  chemical: "'chemical entity'"

data_list_vars:
  syns: xsd:string   # placeholder for synonym list
  syns2: xsd:string   # placeholder for synonym list
  orcid: xsd:string  # ORCID of contributor

name:
  text: "trait in response to %s"
  vars:
    - chemical

annotations:
  - annotationProperty: exact_synonym
    text: "response to %s trait"
    vars:
      - chemical

  - annotationProperty: contributor
    value: orcid

  - annotationProperty: exact_synonym  # this does not work 
    value: syns  # this does not work

exact_synonym:  # this works
  value: syns2   # this works
```
